# Netlify configuration for SPA frontend with API proxy

[build]
  base = "client"
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://api.zebulonhub.xyz/:splat"
  status = 200
  force = true
  # Proxies API requests to backend

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # SPA fallback for client-side routing
