# Netlify configuration for SPA routing and API proxy
[build]
  command = "npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.zebulonhub.xyz/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
