packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - keccak
  - keytar
  - utf-8-validate

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
