"use client";
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollapsibleContent = exports.CollapsibleTrigger = exports.Collapsible = void 0;
var CollapsiblePrimitive = require("@radix-ui/react-collapsible");
var Collapsible = CollapsiblePrimitive.Root;
exports.Collapsible = Collapsible;
var CollapsibleTrigger = CollapsiblePrimitive.CollapsibleTrigger;
exports.CollapsibleTrigger = CollapsibleTrigger;
var CollapsibleContent = CollapsiblePrimitive.CollapsibleContent;
exports.CollapsibleContent = CollapsibleContent;
